### ISSUE TITLE
Can't find vsix file

### ISSUE THREAD

**Issue by yannduran** [timheuer/openvsixpublish#2]
I'm using the same yaml file that @madskristensen uses in his Markdown v2 extension repo, with the sole exception of having `version-type: revision` instead of `version-type: revision`.

The vsix artifact gets downloaded successfully:
> Artifact **extensibility-logs-64-bit.vsix** was downloaded to **D:\a\extensibility-logs-64-bit\extensibility-logs-64-bit**
Artifact download has finished successfully

But then the upload to VSIX Gallery step fails:
>Line |
  24 |  [byte[]]$bytes = [System.IO.File]::ReadAllBytes($vsixFile)
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "ReadAllBytes" with "1" argument(s): "Could not find file
     | '**D:\a\extensibility-logs-64-bit\extensibility-logs-64-bit\extensibility-logs-64-bit.vsix**'."

Comparing the two paths they're identical, so I can't figure out what's going wrong here.

Action's complete yaml file:
```
yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]
      
jobs:
  build:
    outputs:
      version: ${{ steps.vsix_version.outputs.version-number }}
    name: Build 
    runs-on: windows-2022
    env:
      Configuration: Release
      DeployExtension: False
      VsixManifestPath: src\source.extension.vsixmanifest
      VsixManifestSourcePath: src\source.extension.cs
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'

    - name: Increment VSIX version
      id: vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        version-type: revision
        manifest-file: ${{ env.VsixManifestPath }}
        vsix-token-source-file: ${{ env.VsixManifestSourcePath }}

    - name: Build
      run: msbuild /v:m -restore /p:OutDir=\_built
      
    - name: Setup test
      uses: darenm/Setup-VSTest@v1

    #- name: Test
    #  run: vstest.console.exe \_built\*test.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.vsix
        path: /_built/**/*.vsix

  publish:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Package artifact
        uses: actions/download-artifact@v2 
        with:
          name: ${{ github.event.repository.name }}.vsix

      - name: Upload to Open VSIX Gallery
        uses: timheuer/openvsixpublish@v1
        with:
          vsix-file: ${{ github.event.repository.name }}.vsix

      - name: Tag and Release
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') }}
        id: tag_release
        uses: softprops/action-gh-release@v0.1.13
        with:
          body: Release ${{ needs.build.outputs.version }}
          tag_name: ${{ needs.build.outputs.version }}
          files: |
            **/*.vsix

      - name: Publish extension to Marketplace
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') }}
        uses: cezarypiatek/VsixPublisherAction@0.1
        with:
          extension-file: '${{ github.event.repository.name }}.vsix'
          publish-manifest-file: 'vs-publish.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

**Comment by timheuer** [comment]
Hi @yannduran can you clarify which upload is failing? the OpenVsixGallery or the Marketplace...and do you have a link to a failed run?

**Comment by yannduran** [comment]
Sorry about that Tim, I thought I'd been clear when I said "_the upload to VSIX Gallery step fails_". I notice you seem to call it Open VSIX Gallery, and yes technically that's its' name, but we always just call it the VSIX Gallery.

Thanks for the quick reply!

I can't provide a link right now as the repo is currently private.

Does this image help?

![image](https://user-images.githubusercontent.com/2031126/153111937-77119d9c-94ea-4191-b9a8-d99c971e0496.png)

I guess I should have included the image to start with, but I thought my description would be enough.

HTH

**Comment by timheuer** [comment]
Okay, let me think about what the issue may be -- was hoping to see the other details in the logs, etc on build outputs etc, but I think above shows the artifact download fine.

**Comment by timheuer** [comment]
@yannduran is the upload artifact step uploading multiple VSIX files? Like when you look at the summary of this job, and download the artifacts is it a single zip with a single file in it?

**Comment by yannduran** [comment]
No there's only one vsix file.

![image](https://user-images.githubusercontent.com/2031126/153118455-d1f82b4b-099e-4335-92cf-c799667debed.png)

**Comment by timheuer** [comment]
Ok @yannduran, for giggles, on the publish step, change the agent to be `windows-latest` -- it *shouldn't* make a difference, but that is the only delta I can see here from other ones that work.

**Comment by yannduran** [comment]
OK I can try that. I appreciate your help!

**Comment by yannduran** [comment]
Nah, same error unfortunately. 

[build,.yaml.txt](https://github.com/timheuer/openvsixpublish/files/8029242/build.yaml.txt)

It's a weird one isn't it!

**Comment by yannduran** [comment]
Actually, it was already windows-latest in the Publish step. What I just changed turned out to be the Build step.

**Comment by timheuer** [comment]
@yannduran I'm stumped staring at it. I feel like it's something stupid I'm not seeing but everything looks right.  A couple of things you could try to debug (what I'd do):
- Look at the `$vsixFile` var how it's being evaluated (about 4 lines before this in the log should show it.  It should be `"extensibility-logs-64-bit.vsix"`
- Change to a hard-coded name in the download artifact/input to the publish step (like foo.vsix) -- I'm wondering if some dumb pathing length/name thing here
- Scream into the void if none of these work

**Comment by yannduran** [comment]
I could change the name of the vsix itself, but I don't have any control over the total upload/download path though do I? If so I don't know where I'd do that.  I'm new to GitHub actions CI, that's why I just took what was working for Mads.

`D:\a\extensibility-logs-64-bit\extensibility-logs-64-bit\extensibility-logs-64-bit.vsix`.  (87 characters all up)

I do think it's dumb path, but it's made up of repo + project + vsix name. Maybe you could make any suggested alterations to the yaml file I attached and post it back?

**Comment by timheuer** [comment]
Correct you don't have control over the path as that's where the checkout path is.  I'm just a bit amis what the issue is -- just created a simple one myself and https://github.com/timheuer/VSIXProject1/actions/runs/1816146000 it works fine.  Basically anywhere you had `${{ github.event.repository.name }}.vsix` I was suggesting changing to `foo.vsix` hard-coded.  I'm gonna try this same path and see.  and you're confident the artifact is uploading correct? Even in a failed build you should be able to see it:
![image](https://user-images.githubusercontent.com/4821/153122033-dea40740-d326-4d41-a580-754e2fb00127.png)

**Comment by timheuer** [comment]
OOOOHHHH I have a theory...let me test it out.

**Comment by timheuer** [comment]
@yannduran Dang, I cannot test my theory :-).  I am thinking that because this is a private repo having an external action try to copy a downloaded artifact and read it might be blocked somehow.  Since my own repos are /timheuer and the action is /timheuer it's the same org and I can't validate if my theory is correct.  I need someone else to create a private repo (like fork this one then make private: https://github.com/timheuer/VSIXProject1) and see if it still works on submitting a change.

Alternate option (and what would be needed if this is the case and you'll be keeping it private) is to extract the action script and just embed the powershell script within your workflow explicitly.

**Comment by yannduran** [comment]
Yes, the vsix is there, I was able to download it from the summary page. I've renamed it as a .zip so the contents can be examined.

[extensibilitylogs-64-bit.vsix.zip](https://github.com/timheuer/openvsixpublish/files/8029437/extensibilitylogs-64-bit.vsix.zip)

The [link](https://github.com/timheuer/VSIXProject1/actions/runs/1816146000) you posted gave me a 404.

I hope your theory proves true :-)

**Comment by timheuer** [comment]
@yannduran I tried using the same repo name and no issues -- has to be something with private repo file read.  I'll start searching but you may be able to validate it for me quicker if you can try (i remade that repo public)

**Comment by yannduran** [comment]
It won't permanently be a private repo. I'll be uploading it to a public repo soon, hopefully the next day or so. I'll see if that alleviates the problem. It's not blocking me, I can manually upload the file to the gallery. I was just wanting to see how all the magic "just worked" lol

As you said , dang it (we don't say that here is Australia), you can't make a fork private. I'll clone it and upload to a public repo and see what happens. If that turns out to be the problem, at least you will have learned something.

On another note. I've been pronouncing your surname in my head as hoy-er (as it would be in German), but I heard Mads say your name the other day on his show and he said hew-er.

**Comment by timheuer** [comment]
If I can create a similar scenario (or if you try) I'd be very curious if my theory holds (I've also raised it with a few GitHub folks that may know)...it kinda makes sense that something may block it, but weird.  

And yes, that's the correct German pronunciation of course...those Ellis Island guards just decided to enforce it differently many many years ago.  I answer to both...I've been called worse.

**Comment by yannduran** [comment]
Oh good, I don't have to change the way my mind pronounces it t lol

Ellis Island?

Sprichst du übrigens Deutsch? (if you do, yes I know I'm using the informal, not the formal)

I'm trying your suggestion.

**Comment by timheuer** [comment]
Nur ein bisschen

**Comment by yannduran** [comment]
Nope, it didn't fail.

![image](https://user-images.githubusercontent.com/2031126/153125889-7781c11e-dabc-4cec-b5e7-ff9953db51a9.png)

**Comment by yannduran** [comment]
Ich auch ein bisschen

**Comment by timheuer** [comment]
> Nope, it didn't fail.
> 
Well that sucks...I'm outta ideas.

**Comment by yannduran** [comment]
sigh...

Hopefully one of your GitHub friends may have an idea. I'll be trying it with another repo, so I'll see what happens there, and I'll let you know.

**Comment by timheuer** [comment]
I assume if you add this after the download artifact it properly shows the file there and in the right place (as it already indicated success in the `download-artifact` step anyway: https://github.com/timheuer/VSIXProject1/blob/main/.github/workflows/VSIXProject1.yaml#L65-L67

**Comment by yannduran** [comment]
Umm, I'm not sure what you mean. In the summary? Yes, I downloaded it from there and attached it before as a zip.

Oops, sorry I see what you mean now. I'll give it a go.

**Comment by yannduran** [comment]
I also added this when I saw it, but it made the publish step fail. `steps.downloaded.outputs.download-path` must have been blank.
```      - name: Echo downloaded path
        run: echo ${{ steps.downloaded.outputs.download-path }}
```
I'll remove it and try again. Sorry, I know it's late over there. No need to keep replying straight away. As I said it's not blocking me.

**Comment by yannduran** [comment]
Yup, the file's right where it's supposed to be.

![image](https://user-images.githubusercontent.com/2031126/153127994-4eb47ddc-d6d2-4017-9ba2-0bf100cf48ec.png)

**Comment by timheuer** [comment]
WHOA DID WE JUST SOLVE IT @yannduran ?!?! Look at the VSIX name -- it's `extensibilitylogs-64-bit.vsix` and NOT `extensibility-logs-64-bit.vsix` -- notice no `-` between extensibility and logs!

**Comment by yannduran** [comment]
OMG how did that happen???

**Comment by timheuer** [comment]
I can't believe we didn't see it in your other screenshot -- I knew it had to be something so friggin simple.

**Comment by yannduran** [comment]
Dang it (again)! When it first failed I changed the assembly name to match what it was expecting (& hence the vsix name) from `ExtensibilityLogs` to `extensibilitylogs-64-bit` (without noticing the missing hyphen).

Yeah I didn't notice it because it should never have had the hyphen missing! lol

OK, I'll try it again. It failed originally because the assembly name was making the vsix come out as something different from what was expected. When I "fixed" it, I still made it fail.

I even had just temporarily made the repo public to double-check that wasn't somehow still the problem. But you found the cause!

I'll go through again, and let you know, but I'm sure that's gonna be it now that I see it hehe.

**Comment by yannduran** [comment]
Yay! It worked!!!

![image](https://user-images.githubusercontent.com/2031126/153130233-fe75d056-20b6-49a0-8cb7-c778adab3256.png)

Thank you so much for all the time you've spent on this. And I'm so sorry it turned out to be my fault all along. Shop-blindness.

**Comment by yannduran** [comment]
@madskristensen

Tim has added two test vsixes to the VSIX Gallery while helping me sort out this issue. We **_still_** can't delete the vsixes that we upload ourselves, so could you please delete these two so they don't clutter up the list unnecessarily?

![image](https://user-images.githubusercontent.com/2031126/153133322-3466803d-2a44-4d4b-9cbd-71e541f743fa.png)

Thanks!
